import { Download, FileText } from "lucide-react";
import type { FilmBlueprint } from "@/types";

interface ExportActionsProps {
  blueprint: FilmBlueprint;
}

export function ExportActions({ blueprint }: ExportActionsProps) {
  const hasContent = Object.values(blueprint).some((v) => v);
  
  if (!hasContent) return null;

  const exportAsTxt = () => {
    const content = `SCRIPTORIA FILM BLUEPRINT
═══════════════════════════════════════════════════════════

📖 STORY & STRUCTURE
───────────────────────────────────────────────────────────
${blueprint.story}

🫂 CHARACTER ARCS
───────────────────────────────────────────────────────────
${blueprint.characters}

🎨 CHARACTER DESIGN
───────────────────────────────────────────────────────────
${blueprint.characterDesign}

📍 LOCATIONS
───────────────────────────────────────────────────────────
${blueprint.locations}

🎞 SCREENPLAY
───────────────────────────────────────────────────────────
${blueprint.screenplay}

📋 STORYBOARD NOTES
───────────────────────────────────────────────────────────
${blueprint.storyboard}

🎨 VISUAL STYLE GUIDE
───────────────────────────────────────────────────────────
${blueprint.visualStyle}

👔 COSTUME DESIGN
───────────────────────────────────────────────────────────
${blueprint.costumes}

📦 PROPS & SET DESIGN
───────────────────────────────────────────────────────────
${blueprint.props}

🎧 SOUND DESIGN
───────────────────────────────────────────────────────────
${blueprint.sound}

📸 SHOT LIST
───────────────────────────────────────────────────────────
${blueprint.shots}

💡 LIGHTING DESIGN
───────────────────────────────────────────────────────────
${blueprint.lighting}

🎭 CASTING BREAKDOWN
───────────────────────────────────────────────────────────
${blueprint.casting}

🗂 PRODUCTION PLAN
───────────────────────────────────────────────────────────
${blueprint.production}

═══════════════════════════════════════════════════════════
Generated by Scriptoria ✨
`;
    
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "film-blueprint.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex gap-4 mt-6 animate-fade-in">
      <button onClick={exportAsTxt} className="action-button flex items-center justify-center gap-2">
        <Download className="w-4 h-4" />
        Export TXT
      </button>
      <button className="action-button flex items-center justify-center gap-2 opacity-60 cursor-not-allowed">
        <FileText className="w-4 h-4" />
        Export PDF
      </button>
    </div>
  );
}
